USE AIRPORT

--SQL Query to find average price of ticket from BOM To DFW on ’11th May’.
SELECT AVG(PRICE) FROM TICKET2 WHERE DATE_OF_BOOKING=’11-MAY-16’
AND SOURCE= ‘BOM’
AND DESTINATION= ‘DFW’;

--SQL Query to display the details of Flights which are delayed.
SELECT DISTINCT F.FLIGHT_CODE ,AL.AL_NAME ,F.ARRIVAL,F.DEPARTURE,
F.SOURCE, F.DESTINATION, F.STATUS, F.FLIGHTTYPE
FROM AIRLINE AL, AIRPORT AP, FLIGHT F
WHERE AL. AIRLINEID=F.AIRLINEID
AND F.STATUS = ‘Delayed ’;

--SQL Query to display the details of passengers flying to Bombay in economy class.
SELECT
AL.AL_NAME, FL.FLIGHT_CODE, P2.FNAME, P2.LNAME,P2.PASSPORTNO, T.CLASS, T.DATE_OF_TRAVEL, T.DESTINATION, T.SOURCE, T.SEATNO, T.TICKET_NUMBER FROM AIRLINE AL, FLIGHT FL, PASSENGER1 P1, PASSENGER2 P2, PASSENGER3 P3, TICKET1 T
WHERE AL.AIRLINEID = FL.AIRLINEID
AND P1.PID= P3.PID
AND P1.PASSPORTNO =P2.PASSPORTNO
AND FL.FLIGHT_CODE = P3.FLIGHT_CODE
AND T.PASSPORTNO = P2.PASSPORTNO
AND T.CLASS='ECONOMY' AND T.DESTINATION='BOM';

--SQL Query to find the average age of passengers traveling from BOM to DFW.
SELECT AVG(AGE) FROM PASSENGER2 WHERE PASSPORTNO IN (SELECT P.PASSPORTNO FROM PASSENGER1 P, TICKET1 T WHERE P. PASSPORTNO=T.PASSPORTNO AND P.PID=T.PID AND T.SOURCE= ‘BOM’ AND T.DESTINATION=‘DFW’)

--SQL Query to find the number of employees who work in India’.
SELECT COUNT(*) FROM EMPLOYEE1 WHERE AP_NAME IN
(SELECT AP_NAME FROM AIRPORT WHERE COUNTRY=‘INDIA’);

--SQL Query to display passport number and ticket number of passengers flying to Delhi along with their flight name and flight code
SELECT AL_NAME,FLIGHT.FLIGHT_CODE, TICKET1.TICKET_NUMBER, TICKET1.PASSPORTNO
FROM TICKET1 FULL OUTER JOIN FLIGHT
ON TICKET1.SOURCE = FLIGHT.SOURCE
AND TICKET1.DESTINATION=FLIGHT.DESTINATION
FULL OUTER JOIN AIRLINE ON FLIGHT.AIRLINEID = AIRLINE.AIRLINEID
WHERE TICKET1.DESTINATION='DEL'

--SQL Query to figure out which employees are serving which passengers.
SELECT EMPLOYEE1.SSN, FNAME,LNAME, PID, PASSPORTNO, JOBTYPE
FROM EMPLOYEE1 FULL OUTER JOIN SERVES
ON EMPLOYEE1.SSN = SERVES.SSN;

--SQL Query to find out the ssn and job type of employees who work at the airport but do not serve any passenger
SELECT E.SSN,E.FNAME,E.JOBTYPE
FROM EMPLOYEE1 E
WHERE NOT EXISTS (SELECT * FROM SERVES S WHERE E.SSN =S.SSN );