/*USE AIRPORT
CREATE TABLE TICKET_PRICE_HISTORY
(DATE_OF_BOOKING DATE NOT NULL,
SOURCE VARCHAR(3) NOT NULL,
DESTINATION VARCHAR(3) NOT NULL,
CLASS VARCHAR(15) NOT NULL,
PRICE INT,
PRIMARY KEY(DATE_OF_BOOKING, SOURCE, DESTINATION, CLASS));
*/
CREATE TRIGGER TRIGG_TICKET_PRICE_HISTORY ON TICKET2 FOR UPDATE 
AS
DECLARE @DATE_OF_BOOKING DATE;
DECLARE @SOURCE VARCHAR(3);
DECLARE @DESTINATION VARCHAR(3);
DECLARE @CLASS VARCHAR(15);
DECLARE @PRICE INT;
SELECT @DATE_OF_BOOKING= i.DATE_OF_BOOKING from inserted i;
SELECT @SOURCE= i.SOURCE from inserted i;
SELECT @DESTINATION= i.DESTINATION from inserted i;
SELECT @CLASS= i.CLASS from inserted i;
SELECT @PRICE= i.PRICE from inserted i;
BEGIN
IF UPDATE(PRICE) 
	BEGIN
		INSERT INTO TICKET_PRICE_HISTORY(DATE_OF_BOOKING,SOURCE,DESTINATION,CLASS,PRICE)
		VALUES(@DATE_OF_BOOKING,@SOURCE,@DESTINATION,@CLASS,@PRICE);
	END
END
GO


UPDATE TICKET2 SET PRICE=40000 WHERE DATE_OF_BOOKING='2016-06-26'
SELECT * FROM TICKET_PRICE_HISTORY
SELECT * FROM TICKET2 WHERE DATE_OF_BOOKING='2016-06-26'


